name: 버그 리포트
description: 오류나 예외 상황 보고
title: "[bug] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    attributes:
      label: 문제 설명
      placeholder: 어떤 문제가 발생했는지 자세히 작성해주세요
    validations:
      required: true

  - type: textarea
    attributes:
      label: 상황 설명
      placeholder: 어떤 상황에서 문제가 발생했나요?